travis:
  secure:
    BINSTAR_TOKEN: vR+yRMLZFPq5jItQ3U77TKoOxCP5+573FzhhMidfNRZemPe9kKSa+hhvowuv4b4fx8a87xCLP7fXg+eF0Fx20NCHo/ys7NY07sZeV8H63pehEh2NnDL5+MeKEVjdF0UJqvgX/Fh+IuHc9HeGnYGHxH99Ee7fC0Dp7mOFL9L7wiK5M/SpzOY8NJfWE/lKfrjCWjmgj98MprkmzGoleBMau22k9EUmHiZmZ3m5nrRZpVj4Ww8vUSfEJR/MTxq627tqVDIE5NEcHDHrk4zWwv0cNF3+dsJKJT5JIOuLbx93WwzXe45aB8m/41FKBScK/z6T3B5kbn0+CC93B/3Y2HSC+FRGQvudqviVDPjnFVJNWfA07ZANBLC1yKsovLvD/7xpRSjnpFZj3oir0nFk1gaYur1V2ZAbvWNhZQNTaSMu/DhrnwlOpe1tHwDgUgJQQFpq2QK7lj/I4i06vlUbdKyt5M5fD6sIPgwqD+BvGRqDla/Oi3/bT0iKyfJAjA1sEI/zxnsMfDvzLHOGyHU9ckTLOqIAYWw2GeTpo0JALCZSeA1lGvaSwzbsJvLkOhBmdhsTAjTQf0HvHFuosIgYPTtVXN0Jcp0tLso0ONJkllTFM9JfiY8RvQEQ4unIKF/3NWGcAeaAriPtImEU1R/Hs+eSLi66Hdw6avQxejkZheE0TtU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
